site_name: '${{ values.name }}'
site_description: 'Comprehensive documentation for the ${{ values.name }} service'
repo_url: https://github.com/azurelaboratory/${{ values.name }}
edit_uri: edit/main/docs

plugins:
  - techdocs-core
  - kroki

nav:
  - Overview: 'index.md'
  - Architecture: 'architecture.md'
  - Development Guide: 'development.md'
  - Operations Runbook: 'runbook.md'
  - Architectural Decisions:
    - 'ADR Index': 'adr/index.md'
    - 'ADR-001 Container Base Image': 'adr/adr-001-container-base-image.md'