site_name: 'python-app'
site_description: 'Main documentation for the python-app'
repo_url: https://github.com/rodmhgl/python-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview:
      - Getting Started: 'docs/index.md'
