replicaCount: 1
image:
  repository: rodstewart/python-app
  pullPolicy: IfNotPresent
  tag: 084cbde
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  enabled: true
  className: "nginx"
  hosts:
    - host: python-app.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: python-app-tls
      hosts:
        - python-app.azurelaboratory.com
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
