app:
  title: Backstage Kube-Playground
  listen:
    host: 0.0.0.0
    port: 7007
  baseUrl: http://backstage.azurelaboratory.com:7007
backend:
  baseUrl: http://backstage.azurelaboratory.com:7007
  listen:
    port: 7007
    host: 0.0.0.0

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: 5432
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName


catalog:
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ./entities/users.yaml
      rules:
        - allow: [User]

    - type: file
      target: ./entities/groups.yaml
      rules:
        - allow: [Group]

    - type: url
      target: https://github.com/rodmhgl/backstage-software-templates/blob/main/python-app/template.yaml
      rules:
        - allow: [Template]


techdocs:
  builder: 'local'
  publisher:
    type: 'local'
  generator:
    runIn: local


integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}