redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.azurelaboratory.com

server:
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-dns
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    enabled: true
    ingressClassName: nginx
    tls: true
    hosts:
      - host: argocd.azurelaboratory.com
        paths:
        - path: /
          pathType: ImplementationSpecific
        tls:
          - secretName: argocd-server-tls
            hosts:
              - argocd.azurelaboratory.com
